version: '3'

services:
  container1:
    build:
      context: .
      dockerfile: ./Dockerfile

    volumes:
      - ./:/home/workdir/app
    working_dir: /home/workdir/app
    ports:
      - 3002:3002
    tty: true