# Generated by Django 2.2.7 on 2019-11-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift_app', '0002_learners_list_part_time_worker_period_list_period_needs_list_request_work_time_skill_count_adjust_sk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='person',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
